sudo: required

notifications:
  email: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

os:
  - linux

virtualenv:
  system_site_packages: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3    # give xvfb some time to start
  - "xauth generate :99.0 . trusted"
  - "sudo apt-get install xclip"
  - xclip -help
  - "sudo apt-get install -qq python-xlib"

script: python pywinauto/unittests/test_mouse.py
